"""
报告生成器 - 专门用于生成结果报告的模块

提供多种报告生成方式：
1. 基于 WorkLog 的自动报告生成
2. 基于模板的结构化报告生成
3. 专门的 ReportAgent 用于复杂报告场景
"""

import asyncio
import logging
from typing import Dict, Any, Optional, List
from dataclasses import dataclass, field
from enum import Enum
import json

from derisk.agent.expand.react_master_agent.work_log import (
    WorkLogManager,
    WorkEntry,
    WorkLogSummary,
)

logger = logging.getLogger(__name__)


class ReportFormat(str, Enum):
    """报告格式"""

    MARKDOWN = "markdown"  # Markdown 格式
    HTML = "html"  # HTML 格式
    JSON = "json"  # JSON 格式
    PLAIN_TEXT = "plain"  # 纯文本格式


class ReportType(str, Enum):
    """报告类型"""

    SUMMARY = "summary"  # 摘要报告
    DETAILED = "detailed"  # 详细报告
    TECHNICAL = "technical"  # 技术报告
    EXECUTIVE = "executive"  # 执行摘要
    PROGRESS = "progress"  # 进度报告
    FINAL = "final"  # 最终报告


@dataclass
class ReportSection:
    """报告章节"""

    title: str
    content: str
    level: int = 1  # 1-6, 对应 markdown 标题级别


@dataclass
class ReportMetadata:
    """报告元数据"""

    report_type: ReportType
    format: ReportFormat
    generated_at: float
    task_id: str
    agent_id: str
    work_log_stats: Dict[str, Any]
    total_actions: int
    success_rate: float
    duration_seconds: float


@dataclass
class Report:
    """完整报告"""

    metadata: ReportMetadata
    sections: List[ReportSection] = field(default_factory=list)
    raw_data: Dict[str, Any] = field(default_factory=dict)

    def to_markdown(self) -> str:
        """转换为 Markdown 格式"""
        lines = [
            f"# {self.metadata.report_type.value.title()} Report",
            "",
            f"**Generated by:** {self.metadata.agent_id}",
            f"**Task ID:** {self.metadata.task_id}",
            f"**Generated at:** {self._format_timestamp(self.metadata.generated_at)}",
            "",
            "---",
            "",
        ]

        # 总体统计
        lines.extend(self._generate_summary_section())
        lines.append("")

        # 各个章节
        for section in self.sections:
            heading = "#" * section.level
            lines.append(f"{heading} {section.title}")
            lines.append("")
            lines.append(section.content)
            lines.append("")

        return "\n".join(lines)

    def to_html(self) -> str:
        """转换为 HTML 格式"""
        html_parts = [
            "<!DOCTYPE html>",
            "<html>",
            "<head>",
            "<meta charset='utf-8'>",
            "<title>"
            + f"{self.metadata.report_type.value.title()} Report"
            + "</title>",
            "<style>",
            "body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }",
            ".metadata { background: #f4f4f4; padding: 15px; border-radius: 5px; margin-bottom: 20px; }",
            ".summary { background: #e8f4f8; padding: 15px; border-left: 4px solid #1976d2; margin-bottom: 20px; }",
            ".section { margin-bottom: 30px; }",
            "</style>",
            "</head>",
            "<body>",
            "<h1>" + f"{self.metadata.report_type.value.title()} Report" + "</h1>",
            self._generate_html_metadata(),
            self._generate_html_summary(),
        ]

        # 各个章节
        for section in self.sections:
            html_parts.append(f'<div class="section">')
            heading_level = min(section.level, 6)
            html_parts.append(f"<h{heading_level}>{section.title}</h{heading_level}>")
            html_parts.append(f"<div>{self._markdown_to_html(section.content)}</div>")
            html_parts.append("</div>")

        html_parts.extend(
            [
                "</body>",
                "</html>",
            ]
        )

        return "\n".join(html_parts)

    def to_json(self) -> str:
        """转换为 JSON 格式"""
        return json.dumps(
            {
                "metadata": {
                    "report_type": self.metadata.report_type.value,
                    "format": self.metadata.format.value,
                    "generated_at": self.metadata.generated_at,
                    "task_id": self.metadata.task_id,
                    "agent_id": self.metadata.agent_id,
                },
                "summary": {
                    "total_actions": self.metadata.total_actions,
                    "success_rate": self.metadata.success_rate,
                    "duration_seconds": self.metadata.duration_seconds,
                },
                "sections": [
                    {
                        "title": s.title,
                        "content": s.content,
                        "level": s.level,
                    }
                    for s in self.sections
                ],
                "raw_data": self.raw_data,
            },
            indent=2,
            ensure_ascii=False,
        )

    def to_plain_text(self) -> str:
        """转换为纯文本格式"""
        lines = [
            f"{self.metadata.report_type.value.upper()} REPORT",
            "=" * 80,
            "",
            f"Generated by: {self.metadata.agent_id}",
            f"Task ID: {self.metadata.task_id}",
            f"Generated at: {self._format_timestamp(self.metadata.generated_at)}",
            "",
            "-" * 80,
            "",
        ]

        # 总体统计
        lines.extend(self._generate_summary_section_plain())
        lines.append("")

        # 各个章节
        for section in self.sections:
            lines.append(section.title.upper())
            lines.append("-" * len(section.title))
            lines.append(section.content)
            lines.append("")

        return "\n".join(lines)

    def _format_timestamp(self, ts: float) -> str:
        """格式化时间戳"""
        from datetime import datetime

        return datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")

    def _generate_summary_section(self) -> List[str]:
        """生成摘要章节（Markdown）"""
        return [
            "## Executive Summary",
            "",
            f"- **Total Actions:** {self.metadata.total_actions}",
            f"- **Success Rate:** {self.metadata.success_rate:.1%}",
            f"- **Duration:** {self.metadata.duration_seconds:.1f} seconds",
            "",
        ]

    def _generate_summary_section_plain(self) -> List[str]:
        """生成摘要章节（纯文本）"""
        return [
            "EXECUTIVE SUMMARY",
            "",
            f"Total Actions: {self.metadata.total_actions}",
            f"Success Rate: {self.metadata.success_rate:.1%}",
            f"Duration: {self.metadata.duration_seconds:.1f} seconds",
            "",
        ]

    def _generate_html_metadata(self) -> str:
        """生成 HTML 元数据"""
        return f"""
<div class="metadata">
    <h3>Report Metadata</h3>
    <p><strong>Agent:</strong> {self.metadata.agent_id}</p>
    <p><strong>Task ID:</strong> {self.metadata.task_id}</p>
    <p><strong>Generated:</strong> {self._format_timestamp(self.metadata.generated_at)}</p>
</div>
"""

    def _generate_html_summary(self) -> str:
        """生成 HTML 摘要"""
        return f"""
<div class="summary">
    <h3>Summary</h3>
    <p><strong>Total Actions:</strong> {self.metadata.total_actions}</p>
    <p><strong>Success Rate:</strong> {self.metadata.success_rate:.1%}</p>
    <p><strong>Duration:</strong> {self.metadata.duration_seconds:.1f} seconds</p>
</div>
"""

    def _markdown_to_html(self, markdown: str) -> str:
        """简单的 Markdown 转 HTML"""
        html = markdown
        # 简单处理，实际应使用 markdown 库
        html = html.replace("\n\n", "</p><p>")
        html = html.replace("**", "<strong>").replace("**", "</strong>")
        return f"<p>{html}</p>"


class ReportGenerator:
    """
    报告生成器

    基于 WorkLog 生成各种类型的报告。
    """

    def __init__(
        self,
        work_log_manager: WorkLogManager,
        agent_id: str,
        task_id: str,
        llm_client: Optional[Any] = None,
        todo_storage: Optional[Any] = None,
        conv_id: Optional[str] = None,
    ):
        """
        初始化报告生成器

        Args:
            work_log_manager: WorkLog 管理器
            agent_id: Agent ID
            task_id: 任务 ID
            llm_client: LLM 客户端（可选，用于 AI 生成报告）
            todo_storage: Todo 存储实例（可选，用于 Todo 报告）
            conv_id: 会话 ID（可选，用于 Todo 报告）
        """
        self.work_log_manager = work_log_manager
        self.agent_id = agent_id
        self.task_id = task_id
        self.llm_client = llm_client
        self.todo_storage = todo_storage
        self.conv_id = conv_id

    async def generate_report(
        self,
        report_type: ReportType = ReportType.SUMMARY,
        report_format: ReportFormat = ReportFormat.MARKDOWN,
    ) -> Report:
        """
        生成报告

        Args:
            report_type: 报告类型
            report_format: 报告格式

        Returns:
            Report 对象
        """
        # 获取 WorkLog 数据
        full_log = await self.work_log_manager.get_full_work_log()
        stats = await self.work_log_manager.get_stats()

        # 计算统计信息
        work_entries = full_log.get("work_log", [])
        summaries = full_log.get("summaries", [])

        total_actions = stats.get("total_entries", 0)
        success_count = sum(1 for e in work_entries if e.get("success", False))
        success_rate = success_count / total_actions if total_actions > 0 else 0

        # 计算持续时间
        duration = 0
        if work_entries and summaries:
            start_time = work_entries[0].get("timestamp", 0)
            end_time = work_entries[-1].get("timestamp", 0)
            duration = end_time - start_time

        # 创建元数据
        metadata = ReportMetadata(
            report_type=report_type,
            format=report_format,
            generated_at=__import__("time").time(),
            task_id=self.task_id,
            agent_id=self.agent_id,
            work_log_stats=stats,
            total_actions=total_actions,
            success_rate=success_rate,
            duration_seconds=duration,
        )

        # 生成报告章节
        sections = self._generate_sections(report_type, work_entries, summaries, stats)

        # 创建报告
        report = Report(
            metadata=metadata,
            sections=sections,
            raw_data={
                "work_log": work_entries,
                "summaries": summaries,
                "stats": stats,
            },
        )

        return report

    def _generate_sections(
        self,
        report_type: ReportType,
        work_entries: List,
        summaries: List,
        stats: Dict,
    ) -> List[ReportSection]:
        """
        根据报告类型生成章节
        """
        sections = []

        if report_type == ReportType.SUMMARY:
            sections = self._generate_summary_sections(work_entries, stats)
        elif report_type == ReportType.DETAILED:
            sections = self._generate_detailed_sections(work_entries, summaries, stats)
        elif report_type == ReportType.TECHNICAL:
            sections = self._generate_technical_sections(work_entries, summaries, stats)
        elif report_type == ReportType.EXECUTIVE:
            sections = self._generate_executive_sections(work_entries, stats)
        elif report_type == ReportType.PROGRESS:
            sections = self._generate_progress_sections(work_entries, stats)
        elif report_type == ReportType.FINAL:
            sections = self._generate_final_sections(work_entries, summaries, stats)

        if self.todo_storage and self.conv_id:
            todo_section = self._generate_todo_section()
            if todo_section:
                if report_type in [ReportType.PROGRESS, ReportType.FINAL]:
                    sections.insert(1, todo_section)
                else:
                    sections.append(todo_section)

        return sections

    def _generate_summary_sections(
        self, entries: List, stats: Dict
    ) -> List[ReportSection]:
        """生成摘要报告章节"""
        sections = []

        # 1. Task Overview
        sections.append(
            ReportSection(
                title="Task Overview",
                content=self._generate_task_overview(entries, stats),
                level=2,
            )
        )

        # 2. Key Achievements
        sections.append(
            ReportSection(
                title="Key Achievements",
                content=self._generate_key_achievements(entries),
                level=2,
            )
        )

        # 3. Results Summary
        sections.append(
            ReportSection(
                title="Results Summary",
                content=self._generate_results_summary(entries),
                level=2,
            )
        )

        return sections

    def _generate_detailed_sections(
        self, entries: List, summaries: List, stats: Dict
    ) -> List[ReportSection]:
        """生成详细报告章节"""
        sections = []

        # 摘要部分的章节
        sections.extend(self._generate_summary_sections(entries, stats))

        # 4. Detailed Execution Log
        sections.append(
            ReportSection(
                title="Detailed Execution Log",
                content=self._generate_execution_log(entries),
                level=2,
            )
        )

        # 5. Phase Breakdown（如果有阶段信息）
        if summaries:
            sections.append(
                ReportSection(
                    title="Work Periods",
                    content=self._generate_work_periods(summaries),
                    level=2,
                )
            )

        return sections

    def _generate_technical_sections(
        self, entries: List, summaries: List, stats: Dict
    ) -> List[ReportSection]:
        """生成技术报告章节"""
        sections = []

        # 1. Technical Overview
        sections.append(
            ReportSection(
                title="Technical Overview",
                content=self._generate_technical_overview(entries, stats),
                level=2,
            )
        )

        # 2. Tool Usage Analysis
        sections.append(
            ReportSection(
                title="Tool Usage Analysis",
                content=self._generate_tool_usage_analysis(entries),
                level=2,
            )
        )

        # 3. Performance Metrics
        sections.append(
            ReportSection(
                title="Performance Metrics",
                content=self._generate_performance_metrics(entries, stats),
                level=2,
            )
        )

        # 4. Error Handling
        sections.append(
            ReportSection(
                title="Error Handling",
                content=self._generate_error_handling(entries),
                level=2,
            )
        )

        return sections

    def _generate_executive_sections(
        self, entries: List, stats: Dict
    ) -> List[ReportSection]:
        """生成执行摘要章节"""
        sections = []

        # 1. Executive Summary
        sections.append(
            ReportSection(
                title="Executive Summary",
                content=self._generate_executive_summary(entries, stats),
                level=2,
            )
        )

        # 2. Key Recommendations
        sections.append(
            ReportSection(
                title="Key Recommendations",
                content=self._generate_key_recommendations(entries),
                level=2,
            )
        )

        # 3. Next Steps
        sections.append(
            ReportSection(
                title="Next Steps",
                content=self._generate_next_steps(entries),
                level=2,
            )
        )

        return sections

    def _generate_progress_sections(
        self, entries: List, stats: Dict
    ) -> List[ReportSection]:
        """生成进度报告章节"""
        sections = []

        # 1. Current Status
        sections.append(
            ReportSection(
                title="Current Status",
                content=self._generate_current_status(stats),
                level=2,
            )
        )

        # 2. Progress Milestones
        sections.append(
            ReportSection(
                title="Progress Milestones",
                content=self._generate_progress_milestones(entries),
                level=2,
            )
        )

        # 3. Pending Work
        sections.append(
            ReportSection(
                title="Pending Work",
                content=self._generate_pending_work(entries),
                level=2,
            )
        )

        return sections

    def _generate_final_sections(
        self, entries: List, summaries: List, stats: Dict
    ) -> List[ReportSection]:
        """生成最终报告章节"""
        sections = []

        # 包含详细的章节
        sections.extend(self._generate_detailed_sections(entries, summaries, stats))

        # 6. Conclusion
        sections.append(
            ReportSection(
                title="Conclusion",
                content=self._generate_conclusion(entries, stats),
                level=2,
            )
        )

        # 7. Appendices
        sections.append(
            ReportSection(
                title="Appendices",
                content=self._generate_appendices(entries, summaries),
                level=2,
            )
        )

        return sections

    # 辅助方法：生成各部分内容
    def _generate_task_overview(self, entries: List, stats: Dict) -> str:
        """生成任务概述"""
        success_count = sum(1 for e in entries if e.get("success", False))
        total = len(entries)

        return f"""
This task was completed with a **{success_count / total * 100:.1f}% success rate**.

**Key Metrics:**
- Total actions performed: {total}
- Successful actions: {success_count}
- Failed actions: {total - success_count}
- Context window usage: {stats.get("usage_ratio", 0):.1%}
"""

    def _generate_key_achievements(self, entries: List) -> str:
        """生成关键成就"""
        # 找到成功的、重要的操作
        important = [
            e
            for e in entries
            if e.get("success")
            and (
                e.get("tags", []).__contains__("important")
                or len(e.get("result", "")) > 100
            )
        ]

        if not important:
            return "All tasks were completed successfully without major issues."

        lines = ["The following key achievements were made:"]
        for i, entry in enumerate(important[:5], 1):
            tool = entry.get("tool", "unknown")
            summary = entry.get("summary", "")[:200]
            lines.append(f"{i}. **{tool}**: {summary}")

        return "\n".join(lines)

    def _generate_results_summary(self, entries: List) -> str:
        """生成结果摘要"""
        successful = [e for e in entries if e.get("success")]
        return f"Successfully completed {len(successful)} operations throughout the task execution."

    def _generate_execution_log(self, entries: List) -> str:
        """生成执行日志"""
        lines = ["Here is the chronological execution log:\n"]
        for entry in entries[-20:]:  # 最近 20 条
            tool = entry.get("tool", "unknown")
            success = "✅" if entry.get("success") else "❌"
            summary = entry.get("summary", "")[:150]
            lines.append(f"{success} **{tool}**: {summary}")

        return "\n".join(lines)

    def _generate_work_periods(self, summaries: List) -> str:
        """生成工作周期"""
        lines = ["The work was conducted in the following periods:\n"]
        for i, summary in enumerate(summaries, 1):
            count = summary.get("compressed_entries_count", 0)
            tools = summary.get("key_tools", [])
            lines.append(
                f"**Period {i}**: {count} actions completed. "
                f"Primary tools: {', '.join(tools[:3])}"
            )

        return "\n".join(lines)

    def _generate_technical_overview(self, entries: List, stats: Dict) -> str:
        """生成技术概述"""
        return f"""
Technical execution details:
- Context window: {stats.get("context_window", 0)} tokens
- Average usage: {stats.get("usage_ratio", 0):.1%}
- Large outputs archived: {sum(1 for e in entries if e.get("full_result_archive"))}
"""

    def _generate_tool_usage_analysis(self, entries: List) -> str:
        """生成工具使用分析"""
        from collections import Counter

        tool_counts = Counter(e.get("tool", "unknown") for e in entries)

        lines = ["Tool usage breakdown:\n"]
        for tool, count in tool_counts.most_common(10):
            lines.append(f"- **{tool}**: {count} times")

        return "\n".join(lines)

    def _generate_performance_metrics(self, entries: List, stats: Dict) -> str:
        """生成性能指标"""
        total = len(entries)
        success = sum(1 for e in entries if e.get("success"))

        lines = [
            "Performance metrics:",
            f"- Overall success rate: {success / total * 100:.1f}%"
            if total > 0
            else "- Overall success rate: N/A",
            f"- Total processing time: {stats.get('current_tokens', 0)} tokens used",
            f"- Compression efficiency: {(1 - stats.get('active_entries', 0) / total) * 100:.1f}%"
            if total > 0
            else "",
        ]

        return "\n".join(filter(None, lines))

    def _generate_error_handling(self, entries: List) -> str:
        """生成错误处理分析"""
        errors = [e for e in entries if not e.get("success")]

        if not errors:
            return "No errors were encountered during execution."

        lines = [f"Encountered {len(errors)} errors:\n"]
        for i, error in enumerate(errors[:5], 1):
            tool = error.get("tool", "unknown")
            result = error.get("result", "")[:100]
            lines.append(f"{i}. **{tool}**: {result}")

        return "\n".join(lines)

    def _generate_executive_summary(self, entries: List, stats: Dict) -> str:
        """生成执行摘要"""
        return self._generate_task_overview(entries, stats)

    def _generate_key_recommendations(self, entries: List) -> str:
        """生成关键建议"""
        return """
Based on the execution results, the following recommendations are made:

1. **Monitor**: Continue monitoring context window usage
2. **Optimize**: Consider optimizing frequently used tools
3. **Documentation**: Maintain clear documentation of tool usage patterns
"""

    def _generate_next_steps(self, entries: List) -> str:
        """生成后续步骤"""
        return "All tasks have been completed successfully. No action required."

    def _generate_current_status(self, stats: Dict) -> str:
        """生成当前状态"""
        status = "Good" if stats.get("usage_ratio", 0) < 0.8 else "Warning"
        return f"Current status: **{status}**\nUsage ratio: {stats.get('usage_ratio', 0):.1%}"

    def _generate_progress_milestones(self, entries: List) -> str:
        """生成进度里程碑"""
        quarter = len(entries) // 4
        points = [0, 1, 2, 3, 4] if quarter == 0 else [i * quarter for i in range(5)]

        lines = ["Progress milestones:\n"]
        for i in points:
            if i < len(entries):
                entry = entries[i]
                time_str = __import__("time").strftime(
                    "%H:%M:%S", __import__("time").localtime(entry.get("timestamp", 0))
                )
                lines.append(f"- {time_str}: {entry.get('summary', '')[:50]}")

        return "\n".join(lines)

    def _generate_pending_work(self, entries: List) -> str:
        """生成待办工作"""
        return "No pending work. All tasks have been completed."

    def _generate_conclusion(self, entries: List, stats: Dict) -> str:
        """生成结论"""
        return """
The task has been successfully completed. All objectives have been met, and all deliverables have been produced.

The system performed reliably throughout the execution, with successful completion of all required actions.
"""

    def _generate_appendices(self, entries: List, summaries: List) -> str:
        """生成附录"""
        return f"""
**Appendices**

- Appendix A: Full execution log ({len(entries)} entries)
- Appendix B: Compressed summaries ({len(summaries)} periods)
- Appendix C: Tool usage statistics

See raw data for complete details.
"""

    def _generate_todo_section(self) -> Optional[ReportSection]:
        """生成 Todo 任务章节"""
        import asyncio
        try:
            if not self.conv_id or not self.todo_storage:
                return None
                
            from derisk.agent.expand.react_master_agent.todo_tools import (
                get_todo_report_for_reportgenerator,
            )
            
            loop = asyncio.get_event_loop()
            todo_data = loop.run_until_complete(
                get_todo_report_for_reportgenerator(self.conv_id, self.todo_storage)
            )
            
            if not todo_data or todo_data["stats"]["total"] == 0:
                return None
            
            content = f"""
**Total Tasks**: {todo_data['stats']['total']}
- ✅ Completed: {todo_data['stats']['completed']}
- 🔄 In Progress: {todo_data['stats']['in_progress']}
- ⏳ Pending: {todo_data['stats']['pending']}

{todo_data['content']}
"""
            return ReportSection(
                title="Task Progress (Todo List)",
                content=content,
                level=2,
            )
            
        except Exception as e:
            logger.error(f"Failed to generate todo section: {e}")
            return None


class ReportAgent:
    """
    专门的报告生成 Agent

    用于生成复杂的、AI 增强的报告。
    """

    def __init__(
        self,
        work_log_manager: WorkLogManager,
        agent_id: str,
        task_id: str,
        llm_client: Optional[Any] = None,
        todo_storage: Optional[Any] = None,
        conv_id: Optional[str] = None,
    ):
        """
        初始化报告 Agent

        Args:
            work_log_manager: WorkLog 管理器
            agent_id: Agent ID
            task_id: 任务 ID
            llm_client: LLM 客户端
            todo_storage: Todo 存储实例
            conv_id: 会话 ID
        """
        self.work_log_manager = work_log_manager
        self.agent_id = agent_id
        self.task_id = task_id
        self.llm_client = llm_client
        self.report_generator = ReportGenerator(
            work_log_manager, agent_id, task_id, llm_client, todo_storage, conv_id
        )

    async def generate_ai_summary(
        self,
        custom_instructions: Optional[str] = None,
    ) -> str:
        """
        使用 AI 生成报告摘要

        Args:
            custom_instructions: 自定义指令

        Returns:
            AI 生成的摘要文本
        """
        if not self.llm_client:
            return "LLM client not available. Please provide llm_client to generate AI summary."

        # 获取 WorkLog 上下文
        work_log_context = await self.work_log_manager.get_context_for_prompt(
            max_entries=50,
            include_summaries=True,
        )

        # 构建 prompt
        system_prompt = """You are an expert report writer. Your task is to analyze the work log and generate a comprehensive, well-structured summary report."""

        user_prompt = f"""Please analyze the following work log and generate a comprehensive summary report:

{work_log_context}

{"Additional instructions: " + custom_instructions if custom_instructions else ""}
"""

        try:
            # 调用 LLM
            from derisk.core import SystemMessage, HumanMessage

            messages = [
                SystemMessage(content=system_prompt),
                HumanMessage(content=user_prompt),
            ]
            response = await self.llm_client.acompletion(messages)

            return response.choices[0].message.content.strip()

        except Exception as e:
            logger.error(f"Failed to generate AI summary: {e}")
            return f"Error generating AI summary: {str(e)}"

    async def generate_comprehensive_report(
        self,
        report_format: ReportFormat = ReportFormat.MARKDOWN,
        include_ai_summary: bool = True,
    ) -> str:
        """
        生成综合报告

        Args:
            report_format: 报告格式
            include_ai_summary: 是否包含 AI 生成的摘要

        Returns:
            报告内容
        """
        # 生成标准报告
        report = await self.report_generator.generate_report(
            report_type=ReportType.DETAILED,
            report_format=report_format,
        )

        # 如果需要 AI 摘要
        if include_ai_summary and self.llm_client:
            ai_summary = await self.generate_ai_summary()

            # 在报告开头添加 AI 摘要
            ai_section = ReportSection(
                title="AI-Generated Executive Summary",
                content=ai_summary,
                level=2,
            )
            report.sections.insert(0, ai_section)

        # 转换为目标格式
        if report_format == ReportFormat.MARKDOWN:
            return report.to_markdown()
        elif report_format == ReportFormat.HTML:
            return report.to_html()
        elif report_format == ReportFormat.JSON:
            return report.to_json()
        else:  # PLAIN_TEXT
            return report.to_plain_text()


# 便捷函数
async def create_report_generator(
    work_log_manager: WorkLogManager,
    agent_id: str,
    task_id: str,
    llm_client: Optional[Any] = None,
    todo_storage: Optional[Any] = None,
    conv_id: Optional[str] = None,
) -> ReportGenerator:
    """创建报告生成器"""
    return ReportGenerator(work_log_manager, agent_id, task_id, llm_client, todo_storage, conv_id)


async def generate_simple_report(
    work_log_manager: WorkLogManager,
    agent_id: str,
    task_id: str,
    report_format: ReportFormat = ReportFormat.MARKDOWN,
    todo_storage: Optional[Any] = None,
    conv_id: Optional[str] = None,
) -> str:
    """
    快速生成简单报告的便捷函数

    Args:
        work_log_manager: WorkLog 管理器
        agent_id: Agent ID
        task_id: 任务 ID
        report_format: 报告格式
        todo_storage: Todo 存储实例
        conv_id: 会话 ID

    Returns:
        报告内容
    """
    generator = await create_report_generator(
        work_log_manager, agent_id, task_id, None, todo_storage, conv_id
    )
    report = await generator.generate_report(
        report_type=ReportType.SUMMARY,
        report_format=report_format,
    )

    if report_format == ReportFormat.MARKDOWN:
        return report.to_markdown()
    elif report_format == ReportFormat.HTML:
        return report.to_html()
    elif report_format == ReportFormat.JSON:
        return report.to_json()
    else:
        return report.to_plain_text()


__all__ = [
    "ReportFormat",
    "ReportType",
    "ReportSection",
    "ReportMetadata",
    "Report",
    "ReportGenerator",
    "ReportAgent",
    "create_report_generator",
    "generate_simple_report",
]
